train_ranking:
  dataset:
    val_size: 0.10
    downsampling: true
    neg_samples: 1_000_000
  training:
    k: 12
    save_model: True
    model_name: lgbm_ranker # lgbm_ranker / null
    params: 
      objective: binary # binary/lambdarank
      boosting_type: gbdt
      metric: auc # auc/map
      scale_pos_weight: 1
      max_depth: 20
      n_estimators: 40
      num_leaves: 100
      learning_rate: 0.1
      verbose: 1
      # eval_at: 12 # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
