santander_dgsr:
  validate: False
  training:
    k: 20
    model_params:
      batch_size: 50
      hidden_size: 50
      epochs: 10
      lr: 0.001
      l2: 0.0001
      user_update: rnn
      item_update: rnn
      user_long: orgat
      item_long: orgat
      user_short: att
      item_short: att
      feat_drop_out: 0.3
      attn_drop_out: 0.3
      layer_num: 3
      item_max_length: 50
      user_max_length: 50
      k_hop: 2