image_embeddings_inference:
  run_id: ed7592e0901945e2b8ba7c937b3da6cb
  image_path: gid-ml-framework-hm-data/01_raw/images_128_128 # gid-ml-framework-hm-data/01_raw/images_128_128 / data/01_raw/images_128_128
  platform: gcp # local / gcp
  batch_size: 64