ranking:
  val_size: 0.15
  training:
    params: 
      objective: lambdarank
      boosting_type: gbdt
      metric: map
      max_depth: 8
      num_leaves: 128
      learning_rate: 0.03
      verbose: 1
      eval_at: 12 # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
