train_ranking:
  val_size: 0.15
  training:
    k: 12
    params: 
      objective: binary # lambdarank
      boosting_type: gbdt
      metric: auc # map
      max_depth: 8
      num_leaves: 128
      learning_rate: 0.01
      verbose: 1
      # eval_at: 12 # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
